export const columns = [
  { key: "id", label: "ID", sortable: true },
  { key: "firstName", label: "First Name", sortable: true, filterable: true },
  { key: "lastName", label: "Last Name", sortable: true },
  { key: "maidenName", label: "Maiden Name", sortable: false },
  { key: "age", label: "Age", sortable: true },
  { key: "gender", label: "Gender", sortable: true },
  { key: "email", label: "Email", sortable: true },
  { key: "phone", label: "Phone", sortable: false },
  { key: "username", label: "Username", sortable: true },
  { key: "birthDate", label: "Birth Date", sortable: true },
  { key: "bloodGroup", label: "Blood Group", sortable: true },
  { key: "height", label: "Height", sortable: true },
  { key: "weight", label: "Weight", sortable: true },
  { key: "eyeColor", label: "Eye Color", sortable: true },

  // commented for simplicity, to see these columns -> uncomment

//   { key: "hair.color", label: "Hair Color", sortable: true },
//   { key: "hair.type", label: "Hair Type", sortable: true },
//   { key: "ip", label: "IP Address", sortable: false },
//   { key: "address.address", label: "Street Address", sortable: false },
//   { key: "address.city", label: "City", sortable: true },
//   { key: "address.state", label: "State", sortable: true },
//   { key: "address.stateCode", label: "State Code", sortable: false },
//   { key: "address.postalCode", label: "Postal Code", sortable: true },
//   { key: "address.coordinates.lat", label: "Lat", sortable: false },
//   { key: "address.coordinates.lng", label: "Lng", sortable: false },
//   { key: "address.country", label: "Country", sortable: true },
//   { key: "macAddress", label: "MAC Address", sortable: false },
//   { key: "userAgent", label: "User Agent", sortable: false },
//   { key: "university", label: "University", sortable: true },
//   { key: "bank.cardExpire", label: "Card Expiry", sortable: true },
//   { key: "bank.cardNumber", label: "Card Number", sortable: false },
//   { key: "bank.cardType", label: "Card Type", sortable: true },
//   { key: "bank.currency", label: "Currency", sortable: true },
//   { key: "bank.iban", label: "IBAN", sortable: false },
//   { key: "company.department", label: "Department", sortable: true },
//   { key: "company.name", label: "Company Name", sortable: true },
//   { key: "company.title", label: "Job Title", sortable: true },
//   { key: "company.address.address", label: "Company Street", sortable: false },
//   { key: "company.address.city", label: "Company City", sortable: true },
//   { key: "company.address.state", label: "Company State", sortable: true },
//   { key: "company.address.stateCode", label: "Company State Code", sortable: false },
//   { key: "company.address.postalCode", label: "Company Postal Code", sortable: true },
//   { key: "company.address.coordinates.lat", label: "Company Lat", sortable: false },
//   { key: "company.address.coordinates.lng", label: "Company Lng", sortable: false },
//   { key: "company.address.country", label: "Company Country", sortable: true },
//   { key: "ein", label: "EIN", sortable: false },
//   { key: "ssn", label: "SSN", sortable: false },
//   { key: "crypto.coin", label: "Crypto Coin", sortable: true },
//   { key: "crypto.wallet", label: "Wallet", sortable: false },
//   { key: "crypto.network", label: "Network", sortable: true },
//   { key: "role", label: "Role", sortable: true }
];
